repoServer:
  image:
    repository: chatwork/argocd-helmfile
    tag: 2.5.5-0.149.0
  containerSecurityContext:
    runAsNonRoot: false
configs:
  cm:
    configManagementPlugins: |
      - name: helmfile
        generate:
          command: ["/bin/sh", "-c"]
          args: ["helmfile -q template --include-crds --skip-tests"]
    resource.customizations.health.argoproj.io_Application: |
      hs = {}
      hs.status = "Progressing"
      hs.message = ""
      if obj.status ~= nil then
        if obj.status.health ~= nil then
          hs.status = obj.status.health.status
          if obj.status.health.message ~= nil then
            hs.message = obj.status.health.message
          end
        end
      end
      return hs

dex:
  enabled: false
notifications:
  enabled: false
