---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:30afb85df0d8f4a92e016c1c54681ecd9ac7d063cc501a13343bfcb570740c32
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
