---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:cf44c757cca3f616900187e228b79250755a69a1de173678b30dbb69d913d807
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
