---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:84306f856af91b2f61590c6c8366835cb9355239bb810b8e0c7613095a2f2c95
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
