---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:6539f16986c6fdaa541c72a328413e07e7dfd75ebe129bf570790f52bee48e37
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
