---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:e6a48587c35bc7f306cc3f4d6ae85448792a757b5cc5c3db3b0a81dc219d7319
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
