---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:389e238f53923cdc45c21cd679d6be820cdfe41f153927f1c1fcb2fd2bbe018e
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
