---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:9185512df1c6fc4b1f80c3460db87332700a915ffb828313400b21e89b2b93dc
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
