---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:50954c9fef606d41934b76cc2f351a808627f5ad1792220592f72779ae660fc5
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
