---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:d175534a4341d5db89632be8516d43941c8fcd2da2933ed0d084213e18783556
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
