---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:0b8d4b51674872383c5a178f84a38063f3909be2fa81afa54e6375bcb6b59f2b
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
