---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:aa6a19315f09c9e1bbc34df492f6792203e90896c3c45c2449cf341bbf6e7561
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
