---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:570742e221db66c3cca9c6a2db10178b5be8b8db8bf788c32929c521b3681a34
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
