---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:87432daf93d5d103578c48d0e02bf4d2a223c630c289d75aef6feee2c2c86d20
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
