---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:3ffad3517219b2cba2f52003d5c8a6ec29205f75aa086f16978a2c495cc41646
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
