---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:cf04bc9f0df9a3cc29f7a5a8427cf1bef1d6265b1a18732fd55143532550c79a
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
