---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:2945b99ab2757c297687e4f907dc412ed440142f2a9f9e25386334e20d55b06e
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
