---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:45541421f115c01fcb1c49465e8e43fff264e1709edbea12222dde4e5046202e
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
