---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:f02890a74444d935cbff1264da6eb6916b8c9987749cbe723f5e05f2c2761f31
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
