---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:b2dcfa87bda3cf1b6f37b8255a6da56fe842c1295825f0c0d833786ca73cab8f
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
