---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:2c47321a94129971dadf45f9271b9ec5b8eee668071e9379156b6b8139d4b56c
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
