---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:99a15437da122cb861531a60ed9c8705627aec92ec6a64028c1876d8b01be4b4
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
