---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:806b92b7ee48d68cb55db75bc96ab940e77b6a4964ce62ae8d41aae9aa514673
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
