---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:03d05e3942b8176dcd2f665547c0d200ede586749f2cc2e717d5f372df72cbc2
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
