---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:70ece3e64b07b0d3f579e396e20dbb4589c0a37e9cffe47057db78c7c2a0f384
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
