---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:df8ccaa632b3e29cb2a18a1d82bda4abf6538e3072f57f6c59c8b31d477ee952
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
