---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:cb1222025f95b6e54e2eecff57a698557fe137890acdb99b0f6e99a0c9115671
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
