---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:8fc7a25084becca5264884e7db9f01aa378f7330f8952cd942c9544aaaf4cf0c
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
