---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:d9a12c8fb5ac1cf91f3f09b1d7a06042da6d0360cb1cca304fbb7fe59368547a
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
