---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:fe0010991cbc52eea9c4e86422ba6a7a2714baac0a6763f6b7c8dcd1ae1f685b
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
