---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:a503e58f36607d22d6b57387e53a9ec298fbcbd9300c9a8c6f38a4055757b768
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
