---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:31fead5806f656e0982161100fe6cffa8ee7519dff724497628dbc4ead8e5167
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
