---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:45f88b9fc0066108c3eecaee9e8818606d02d2efb97d1c5008c9d848c01f7c82
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
