---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:477bc199331c08e99043e7f3d60e0277ace4029464414382092fb358dca5268e
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
