---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:f22523dde5527e7df2d207f4a438487c67bd5597ae2dd91233e9f085b789f188
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
