---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:4021c444325a2e9b48ee13846050e53eda1b38fe0b9e06ffdea82b5c6e12e4c7
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
