---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:81884c3cba17697a5c6c4b943c5a1ecb6dd14f86014f713d05a88737959ef9ec
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
