---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:6650d5084043f119787181f7ef22d0ad921c19e2e47f30896c1d68415d987a3e
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
