---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:ce6682001b95402a67f86fdf9914b3bc30038f8493bc0c9d413825421e8cb2fb
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
