---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:76f32793e1d2a29850b49e8ab2b4a16999822b0ec70b6f2ece20cef3fb1264a2
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
