---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:0affffe3197474cd81be18428833e9c3d83aa9bb7b51dbaa130784653c8f11d3
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
