---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:b14233f183a77b1d1ff660b83edeb20afad6e373b523858411656ac631cd36bc
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
