---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:9f27965329bba640a70e6a98423bc03b67f9f0842806ab8d3c59a5e2cf062a2b
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
