---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:f02f96b33756869ab71fbed8ded74d08379fdd668369b75234053e0be8c91a8b
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
