---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:c3aa8e7be1585de3ee5764888a0e054c01293f85bfb6d9fde69cd2a6428e6e7e
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
