---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:81ebbbb5da5dfaf2808ed2189f98f0e52f211990d48d945a60f9dc904b1affd8
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
