---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:9589882323bdbf5db86c241838e154c7990c76d08a155d00737092a02a2752aa
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
