---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:f9b9d2f58ad82f5b9c36f37ada5fbb9f3ccb3be1e6ca7f374f3d0cefa735d5b4
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
