---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:2e99ed8ba00a4a60d4d3830164681137f65babb6f9baa0be91f199d370f9d557
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
