---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:5ca9f063641285c33157c72cea3c5501b15939a8a3a61fcc605ab1deb76811f4
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
