---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:da7aa2c951e6ce4464b6a439262ce13bc720a489495b8ca55dd1a345c830d556
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
