---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:25abad0c77cd90e8e4d194a0d5778392c019f1fa545efc5d57f329ca7ba4b74e
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
