---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:75f73188c3455e4460b09153ede2a9b5572c9ae07586fdb449918b06d79c2b2a
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
