---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:b2ac14caee3229582a70ce0e27922ca27400e41dfa246a577481858764aa6c89
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
