---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:c0e0c25a2a80de6c844695c41571377071191923baf0a4dd89bc5a58154d828c
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
