---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:002f29b68cbe572953d030db19df5142092b80b540b901f8e0df09db84b1e5c2
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
