---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:0b9267fc3d31bc7304bae1a0bd25ade93141345572fb89757201dec0b2fa8fef
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
