---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:e7e04d3c245a25b06015d45c7ae88a7071dc291aa7b47db25da0ca6d5f1bbf51
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
