---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:52fdee094295ccddacde102660fe1b7b8b7db51e1b372973ec07a779f9a65ba1
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
