---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:c812b078d2caa21c1ea50445d7d9e090ad0a45e3ad497d177d5be23330837b96
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
