---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:309c575ed2285a32c01b21ff8edb4f58de0ce9b78be1a1ae3ac965a6ff3bb84c
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
