---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:779e0589d67512b5860ac5a4fdd8b7843dd1c52be137581ae4b22bdeba1bf1d8
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
