---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:28cd716a96dd8b5875bab2f61b9c5f41ce14dd7661e2306ebea03101cb50693a
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
