---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:41b358a0ab740cb2c490f7d6f245338f7e572ec2a462310728864534ef26c5fc
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
