---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:89e1e9213741b451de38cf87cf73318f7dbd3af582aab6ad2bb683d19ec0b94f
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
