---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:dbb1308edbd5ecec8e8a091bbecd9847340673f8e5409aa97105c8fd976911b2
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
