---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:623565bdc559401a85df43bca66e7dc273a58e2f32954d9ff3f22f8b9c7050a7
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
