---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:72d57f0954c344f2c1e8faf24dcac5413c4f400907154c4d22b67b43c95e1190
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
