---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:c3294935064dbc208ed81aa690a314fe52bedfc090da90735cf9613fb26ac47a
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
