---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:0a1bf43845d14107a976952c8ee2461c53e8ea3827297241b3e8bbc8445a84bf
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
