---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:22fa847f23c93132e24d5b2d6f9244245e2c978d05a94ca8cc4f49c1a98b94b8
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
