---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:4e0c79c946dedd7f827ca947167cef1685488ff8316c3b3d5a2f8359ca738fc1
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
