---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:65cf9b485e129fa696d9cd0f163a1662b64c75b14073152a89e28215cdf47943
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
