---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:9aed2a8eaa36cf3b05bff4be2798c33ef83a44e4b28ddf078303391d96bcc0fa
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
