---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:9102fcc92a1d932b49784e15ebaa24cc7783d0c452772251ec5e4b681d5d3fe7
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
