---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:6f747d01ad06dbf09c3e2b9e299aebae1db8f466ca8ac04ade2c4571eaf5baa9
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
