---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:a8680acfbe622399ed0a38305bee92050a11ef4f11f09799e08144d4ee7f1917
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
