---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:324035dec009edb6025f0f1402f8da398d2ea0294b80212c94f908a06f4551b3
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
