---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:08fff2e6af01d28e1f7002208104b974e89f2c29e3315e8fe8f32e5136c88f1b
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
