---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:4c5b5df39fbeeb603384953ea9ede94684d48811fe44ade0ee6fd90395b99e37
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
