---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:bbe37d1ae0cb3fd431a56c6f00bb594e441880873dd2b1e495a4e40238b2ddad
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
