---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:a9528434e4c1c2a5ff9999a85af8fa6787601a054491eb7c3ccbed216544e1c7
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
