---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:f61b6f012eb4e7932a36ad5e1f48434b420b5aa9d6a1dbc8fba18413241a8316
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
