---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:bcc83df9ffc10de6a4bddfba57d1ec81c739acee5291b2095d9d393bf56c5057
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
