---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:b82f9dc61cbd9e057b9fe9e134f1b6616914a7d9f8f7e3dd3a7933e2667c3eba
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
