---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:36bc5d783174e185e8925af695bf6284ae9d3d5acde126bce08d1998362f9727
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
