---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:d8b0491c3ea860549e2e7cfe4e2f62a98b9e06d182b0becdd17f972431beef7f
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
