---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:3c0614b807ce43254ce26379195877941f7ce0bebdc19378bf9e41cbaddfe651
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
