---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:6099b878a307b2a02c7a05c67643142263dade199ea90c940ac66e6bb6de1e46
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
