---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:e15e1a0c6993af7112f9827c72d24f24ad0b687ccbda5f8b8593177c05b2ab29
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
