---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:3c941ab75928a0742d14b149d7270954b78144b710b3a84fac53b6e2182c0168
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
