---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:5618a7a6414bf28da945ce54e0f56310c4c554532419d4152713fb157afbb256
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
