---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:632b90793dfabe5c4d061a9fb3cf8026e4f07ba6545422a1bd1591f84f020d8d
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
