---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:748a0ed57b1c81a15654fcc526c1506d7899ea67315258dabee3f8d1a1ac0664
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
