---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:b023c091a44d1276f24be0e1de061af75df3158b30d8619363e6a01ece1c183d
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
