---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:038fc7411e5af2daf137a5a04aff1b244f12d96c3d894d9e0c2cfd44d79c49bf
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
