---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:a1c05442c7d6ab4d84b2005ca2e227f7b52be62daf53b256c6fd1b6c85295941
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
