---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:f2753a4878768b18abc8fb337e8419ca0ce81fd9ebd942078590e3c75e34fe28
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
