---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:d4a67df88e0e82017b88124ca9914ee175c25534791f775a099c25c654bc81e1
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
