---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:a733391af18676f56fd91ea9ee25d33a70a9fd6de1bb9fcdc6d87425afcb1316
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
