---
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:116e238216ea51caa3a468cbe4e7eeb32fc5222e2c736e118dd72e2688bcf733
resources:
  - ingress.yaml
  - backend.yaml
  - external-secret.yaml
