
---
apiVersion: v1
kind: Service
metadata:
  namespace: argocd
  name: argocd-port
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-server
  ports:
    - nodePort: 30080
      port: 8080
