---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/YunosukeY/k8s-cd-playground.git
    targetRevision: HEAD
    path: k8s/charts/external-secrets
    plugin:
      name: helmfile
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated: {}
