---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: ingress-nginx
spec:
  project: default
  source:
    repoURL: https://github.com/YunosukeY/k8s-cd-playground.git
    targetRevision: HEAD
    path: k8s/charts/ingress-nginx
    plugin:
      name: helmfile
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
