---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: apps
spec:
  project: default
  source:
    repoURL: https://github.com/YunosukeY/k8s-cd-playground.git
    targetRevision: HEAD
    path: k8s/cd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
