name: kind e2e
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  kind:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v3.0.0
        with:
          aqua_version: v2.25.1
      - run: helm plugin install https://github.com/databus23/helm-diff
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo -n $GITHUB_TOKEN > ./github-pat
          cat <<EOF > access-key.env
          access-key=$AWS_ACCESS_KEY
          secret-access-key=$AWS_SECRET_ACCESS_KEY
          EOF
          ./kind/e2e.sh run
